## Taps

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "railwaycat/emacsmacport"

# Brews

## Replacements for UNIX tools
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Yet another cross-platform graphical process/system monitor
brew "bottom"
# GNU File, Shell, and Text utilities
# brew "coreutils"
# Power of curl, ease of use of httpie
brew "curlie"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# More intuitive version of du in rust
brew "dust"
# Modern replacement for 'ls'
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# Improved top (interactive process viewer)
brew "htop"
# Modern replacement for ps written by Rust
brew "procs"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Intuitive find & replace CLI
brew "sd"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# Cross-platform Rust rewrite of the GNU coreutils
brew "uutils-coreutils"
# Shell extension to navigate your filesystem faster
brew "zoxide"

## Other tools`
# Spell checker with better logic than ispell
brew "aspell"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 3.2
brew "bash-completion"
# Interpreted, interactive, object-oriented programming language
brew "python"
# Perl lib for reading and writing EXIF metadata
# brew "exiftool"
# GNU Transport Layer Security (TLS) Library
# brew "gnutls"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Collection of GNU find, xargs, and locate
# brew "findutils"
# Interpreter for PostScript and PDF
# brew "ghostscript"
# Command-line utility for uploading Gists
brew "gist"
# Distributed revision control system
brew "git"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Compare and mark up LaTeX file differences
brew "latexdiff"
# Implementation of the file(1) command
brew "libmagic"
# GUI for vim, made for macOS
brew "macvim"
# Mac App Store command-line interface
brew "mas"
# Powerful paging program
brew "most"
# Turn marked-up plain text into well-formatted documents
brew "multimarkdown"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Wrapper to colorize and simplify ping's output
brew "prettyping"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Software environment for statistical computing
brew "r"
# RC file (dotfile) management
brew "rcm"
# Safe, concurrent, practical language
brew "rust"
# Rust toolchain installer
# brew "rustup-init"
# SMART hard drive monitoring
brew "smartmontools"
# Modernized, complete, self-contained TeX/LaTeX engine
brew "tectonic"
# Send macOS User Notifications from the command-line
brew "terminal-notifier"
# Programmatically correct mistyped console commands
brew "thefuck"
# CLI tool that moves files or folder to the trash
brew "trash"
# Command-line unarchiving tools supporting multiple formats
brew "unar"
# Internet file retriever
brew "wget"
# UNIX shell (command interpreter)
brew "zsh"
# Additional completion definitions for zsh
brew "zsh-completions"
# Tips, tricks, and examples for zsh
brew "zsh-lovers"
# Fish shell like syntax highlighting for zsh
brew "zsh-fast-syntax-highlighting"


## Casks

# Password manager that keeps all passwords secure behind one password
cask "1password"
# Apple TV Aerial screensaver
cask "aerial"
# Integrated CAD, CAM, CAE, and PCB software
cask "autodesk-fusion360"
# Molecule editor and visualizer
cask "avogadro"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Edit and manage bibliographies
cask "bibdesk"
# Reference management and bibliography software
cask "bookends"
# Scriptable scratchpad for developers
cask "boop"
# Web browser focusing on privacy
cask "brave-browser"
# Calculator software
cask "chalk"
# Tool to list all active shortcuts of the current application
cask "cheatsheet"
# Service provider for Aspell spell checker
# cask "cocoaspell"
cask "colorpicker-developer"
cask "colorpicker-propicker"
# Tool to help searching the web more efficiently
cask "devonagent"
# Collect, organize, edit and annotate documents
cask "devonthink"
# Voice and text chat software
cask "discord"
# YAMAMOTO Mitsuharu's Mac port of GNU Emacs
cask "emacs-mac-spacemacs-icon"
# Web browser
cask "firefox"
# Web browser
cask "google-chrome"
# Free and open-source media player
cask "iina"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Productivity tool
cask "launchbar"
# Full TeX Live distribution with GUI applications
# cask "mactex"
# Open-source Dropbox client
cask "maestral"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Free and open-source RSS reader
cask "netnewswire"
# Scheduling application focusing on organization
cask "omnifocus"
# Visual communication software
cask "omnigraffle"
# Note taking applciation and information organizer
cask "omnioutliner"
# Graphical user interface for the 'defaults' command
cask "prefs-editor"
# Collection of apps available by subscription
cask "setapp"
# PDF reader and note-taking application
cask "skim"
# Backup, recovery and cloning software
cask "superduper"
# Graphical user interface for TeX Live Manager
cask "tex-live-utility"
# General-purpose text editor
cask "textmate"
# Open-source BitTorrent client
cask "transmission"
# 3D printer and slicing GUI
cask "ultimaker-cura"
# Video communication and virtual meeting platform
cask "zoom"

# Fonts
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-inconsolata"
# Typeface made for developers
cask "font-jetbrains-mono"
cask "font-liberation"
cask "font-open-sans"
# Unicode fonts for scientific, technical, and mathematical texts
cask "font-stix"

# QuickLook plugins
cask "qlcommonmark"
cask "syntax-highlight"
cask "quicklook-csv"

## MAS apps

mas "1Blocker", id: 1365531024
mas "1Password for Safari", id: 1569813296
mas "Affinity Designer 2", id: 1616831348
mas "Affinity Photo 2", id: 1616822987
mas "Affinity Designer 2", id: 1606941598
mas "Airmail", id: 918858936
mas "Calca", id: 635758264
mas "DaisyDisk", id: 411643860
mas "Drafts", id: 1435957248
mas "Hush", id: 1544743900
mas "Irvue", id: 1039633667
mas "Microsoft Remote Desktop", id: 1295203466
mas "Pins", id: 1547106997
mas "Pixelmator Pro", id: 1289583905
mas "Slack", id: 803453959
mas "StopTheMadness", id: 1376402589
mas "URL Linker", id: 1289119450
mas "Baking Soda", id: 1601151613
mas "Vinegar", id: 1591303229
mas "Tot", id: 1491071483
# mas "Xcode", id: 497799835

# Apple iWork apps
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541

# Microsoft Office apps
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704

## Setapp
# Menu bar icon organizer
# cask "bartender"
# Utility to create and modify archives
# cask "betterzip"
# Calendar software
# cask "fantastical" # replace with BusyCal
# Finder replacement and FTP, SFTP, WebDAV and Amazon s3 client
# cask "forklift"
# Previewer for Markdown, MultiMarkdown and other text markup languages
# cask "marked2"

## Home

# Casks
# App to manage bank accounts in one place
# cask "banktivity"
# Video game digital distribution service
# cask "steam"
# E-books management software
# cask "calibre"

# MAS
# mas "GarageBand", id: 682658836
# mas "iMovie", id: 408981434
# mas "HP Easy Scan", id: 967004861
# mas "Darkroom", id: 953286746
# mas "Book Track", id: 1496543317

## Work

# Casks

# Collection of apps and services for photography, design, video, web, and UX
# cask "adobe-creative-cloud"
# Open-source image processing package
# cask "fiji"
# 3D printing setup, management, and monitoring
# cask "preform"
# Scientific Python IDE
# cask "spyder"

# MAS apps
# mas "OneDrive", id: 823766827
# mas "Microsoft Outlook", id: 985367838
