schemaVersion = 4

[actionPreferences]
applicationOrderOverrides = []
itemDefaultOverrides = []

    [[actionPreferences.typeOrderOverrides]]
    typeID = 'com.tuna.type.application'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'open'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'reveal'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'toggle-application'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'activate'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'quit'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'kill'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'copy-to-clipboard'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'add-to-catalog'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'add-to-custom-items'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'add-to-shelf'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'always-open-type-with'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'assign-alias'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'browse'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'browse-recents'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'check-for-updates'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'compress'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'compress-to-shelf'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'copy-paths-to-clipboard'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'copy-to'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'do-not-open-at-login'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'get-absolute-posix-path'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'get-file-url'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'get-info'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'get-path'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'hide'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'load-more-results'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'make-alias-in'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'make-link-in'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'move-to-trash'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'move-to'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'open-at-login'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'open-file'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'open-with'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'perform-quick-action'
        catalogIdentifier = 'tuna.quick-actions.actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'pick'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'remove-custom-item'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'rename'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'resolve'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'run-applescript-with-file'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'run-as-prompt'
        catalogIdentifier = 'tuna.prompts.actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'search'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'send-feedback'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'send-keys.from-app'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'send-to-custom-prompt-on-shelf'
        catalogIdentifier = 'tuna.prompts.actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'send-to-custom-prompt'
        catalogIdentifier = 'tuna.prompts.actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'send-to-prompt-on-shelf'
        catalogIdentifier = 'tuna.prompts.actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'send-to-prompt'
        catalogIdentifier = 'tuna.prompts.actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'send-to-script'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'send-to-shortcut'
        catalogIdentifier = 'tuna.shortcuts.actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'send-to-smart-link'
        catalogIdentifier = 'tuna.smart-links.actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'share'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'show-onboarding'
        catalogIdentifier = 'tuna.common-actions'

        [[actionPreferences.typeOrderOverrides.actions]]
        actionID = 'uninstall'
        catalogIdentifier = 'tuna.common-actions'

[catalogConfiguration]
customFolders = []
customItems = []
scriptsDirectories = []

    [[catalogConfiguration.folderDepthOverrides]]
    catalogIdentifier = 'tuna.system-settings'
    depthRawValue = 1

[catalogs]
searchPriorities = []
sortOrders = []

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.contacts'

        [catalogs.globalScopes.scope]
        kind = 'none'

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.effects'

        [catalogs.globalScopes.scope]
        kind = 'none'

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.emoji'

        [catalogs.globalScopes.scope]
        kind = 'none'

[[comboMode.bindings]]
key = 's'
url = 'tuna://run?subject=path:/Applications/Safari.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 't'
url = 'tuna://run?subject=path:/Applications/Ghostty.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 'f'
url = 'tuna://run?subject=path:/System/Library/CoreServices/Finder.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 'm'
url = 'tuna://run?subject=path:/System/Applications/Music.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 'n'
url = 'tuna://run?subject=path:/System/Applications/Notes.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 'o'
url = 'tuna://run?subject=path:/Applications/Orion.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 'd'
url = 'tuna://run?subject=path:/Users/mskblackbelt/Downloads&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 'h'
url = 'tuna://run?subject=path:/Users/mskblackbelt&action=tuna.common-actions/open'

[hotkeys.app.activate]
carbonKeyCode = 49
carbonModifiers = 256

[[hotkeys.custom]]
id = 'D6943468-50B3-45E7-BD30-B5170B779C2C'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'tuna.common-actions/browse'
    subjectIdentifier = 'tuna.clipboard/clipboard.history.root'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 42
    carbonModifiers = 4352

[[hotkeys.custom]]
id = 'FFA88463-4F6A-4A4D-A7FF-761250819CFD'
presentation = 'show'

    [hotkeys.custom.command]
    actionIdentifier = 'tuna.common-actions/stage'
    subjectIdentifier = 'tuna.current-selection/Current Selection'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 49
    carbonModifiers = 768

[settings]
appPresentationMode = 'never'
backspaceBehavior = 'deleteCharacters'
comboModeModifierTrigger = 'rightOption'
comboModeTriggerType = 'modifier'
typingTimeoutDuration = 0.75

[[catalogSettings]]
catalogIdentifier = 'tuna.prompts'

    [catalogSettings.values]
    Provider = 'apple'
