schemaVersion = 1

[hotkeys.app.activate]
carbonKeyCode = 49
carbonModifiers = 256

[[hotkeys.custom]]
id = '3F16C9F7-990E-4CB5-BED2-AA9DD57F6B81'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'Tuna.BasicActionsCatalog.Browse'
    subjectIdentifier = 'Tuna.Internal.ClipboardProxyCatalog.Clipboard History'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 42
    carbonModifiers = 4352

[[leaderMode.bindings]]
key = 's'
url = 'tuna://run/path.%252FApplications%252FSafari.app/Open'

[[leaderMode.bindings]]
key = 't'
url = 'tuna://run/path.%252FSystem%252FApplications%252FUtilities%252FTerminal.app/Open'

[[leaderMode.bindings]]
key = 'f'
url = 'tuna://run/path.%252FSystem%252FLibrary%252FCoreServices%252FFinder.app/Open'

[[leaderMode.bindings]]
key = 'm'
url = 'tuna://run/path.%252FSystem%252FApplications%252FMessages.app/Open'

[[leaderMode.bindings]]
key = 'n'
url = 'tuna://run/path.%252FSystem%252FApplications%252FNotes.app/Open'

[[leaderMode.bindings]]
key = 'd'
url = 'tuna://run/path.%252FUsers%252Fmskblackbelt%252FDownloads/Open'

[[leaderMode.bindings]]
key = 'h'
url = 'tuna://run/path.%252FUsers%252Fmskblackbelt/Open'

[settings]
backspaceBehavior = 'deleteCharacters'
catalogPeriodicRescanIntervalMinutes = 10
leaderModeModifierTrigger = 'rightCommand'
leaderModeTriggerType = 'modifier'
switchToTextModeWhenNoResults = true
themeIdentifier = 'com.brnbw.tuna.themes.default'
typingTimeoutDuration = 1.05

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.themes.default'

    [catalogSettings.values]
    ThemeTint = 'system'